# https://github.com/char-lie/patterns_recognition
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sh install-conda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION numpy scipy
  - source activate testenv
  - pip install -U -r requirements.txt
script: coverage run --source=classes -m tests
after_success: coveralls

